### ISSUE TITLE
Support Answer feedback?

### ISSUE THREAD

**Issue by fuhrmanator** [mattbellis/using-Google-Forms-quizzes-with-a-testbank#1]
Is it possible with your approach to support answer feedback (i.e. "Add explanations to answers")? https://support.google.com/docs/answer/7032287?hl=en I suspect it would require adding another column for each answer (for the feedback)?

I have a [parser for GIFT format that creates JSON objects](https://github.com/fuhrmanator/GIFT-grammar-PEG.js), so I'm wondering if your approach could be integrated (without using a spreadsheet as an intermediate)? GIFT format is in many ways more intuitive (although has its drawbacks).

**Comment by fuhrmanator** [comment]
I just realized that Google Quiz explanations don't allow answer-specific feedback. It only allows one feedback for the correct answers and one for the incorrect. That's OK if a multiple-choice has only two options, but is not so useful for other flavors. I guess I'll wait until Google ramps up their quiz features.

**Comment by mattbellis** [comment]
Just to follow up on your comment, one challenge that I've found with this approach is that Google has not yet exposed the API for the Quiz aspect of Google forms. So I can't actually put in Quiz-specific information (correct answer, points, feedback, etc) when I create the form. It's pretty frustrating. 

My workaround is to copy over a Quiz, add the content with the script, and then manually put in the answer key and feedback. It works...but is suboptimal. :(

**Comment by fuhrmanator** [comment]
Yeah, I think your "hack" was great, even if not perfect. Thanks for following up. Quizzes with feedback are a powerful tool pedagogically speaking, but I'm not sure enough people realize it to make it interesting to companies like Google. They could kill their Quiz support in Forms in 2 years if it doesn't go anywhere.

**Comment by mattbellis** [comment]
Agreed.
