### ISSUE TITLE
How to copy form template

### ISSUE THREAD

**Issue by bsde1234** [mattbellis/using-Google-Forms-quizzes-with-a-testbank#2]
Is it still working, How to copy form template?

**Comment by mattbellis** [comment]
It wasn't before, but now it is. 

There was an image on Wikimedia that I was using for the demo that was not accessible anymore, for some reason. I changed that and now it works...for me at least. Let me know if you have any other problems.

**Comment by bsde1245** [comment]
Ok, I was asking about form template. What i did was create an empty form and put the id of form in app script. But when I run the app form created with different id. Also do we need to run the app every time to create random pick. One more can we automatically shuffle the row in quiz maker sheet which will randomly pick say 50 question numbers out of 100?
